### ISSUE TITLE
Create Data Dictionary

### ISSUE THREAD

**Issue by kielejocain** [hackoregon/emergency-response#40]
Collate information provided by Mark about the various PF&R data into a codebook

**Comment by futurechris** [comment]
My random notes:

- If an incident has both TimeDesc_ID 0 and 1, the '0' represents the start.
- Some incidents may not have a 0/1/2 for TimeDesc_ID, which may indicate something like a truck driving along when they see a fire or other incident, so they stop.
- AMR is the ambulance company
- AMR does TimeDesc_ID 9 for 'left the scene with a patient', 10 for 'arrived at hospital'
- Mark is interested in figuring out the 0 to 3 duration (call processing time)
- Number after a responder unit typically refers to the station ID of the unit
- An effective fire response team (forget the exact name Mark used) is to get 15 firefighters (minimum: 1 battalion chief, 2 engines, 1 truck)) to the scene. Goal is to get this within 12 minutes.
  - They are interested in a variant of the response time that is how long it takes to get all of these units there.
- PF&R is most concerned with getting engines and trucks to the scene as fast as possible, so metrics around those are interesting to them.
- PF&R is not as concerned with time for I### (investigators) or PIO### (public information officer), because these aren't as time-critical.
- Some units are 'special' units: HS## Heavy Squad for chemical/nuclear/etc., TR## Trench rescue, USAR## urban search and rescue
- TimeDesc_IDs 6 and 14 aren't used anymore, apparently.
- Not sure I got this correct, but: The "responderUnit_ID" is the 'first dispatched' unit, but may not correspond to the first one scene, so Mark thinks we should probably ignore that.

Data that was removed from the dataset:
- Location: x_coord/y_coord/latitute/longitude
- Street number
- AptSuite? (Not sure)

**Comment by kielejocain** [comment]
I've given a first go to the Data Dictionary.  Please review and let me know what you think.

[link](https://github.com/hackoregon/emergency-response/wiki/Data-Dictionary)

**Comment by hannahkane** [comment]
looks really good. thanks for compiling.

**Comment by futurechris** [comment]
Agreed - this will be really helpful. Perhaps link and pin in the main channel?

**Comment by markawhitaker** [comment]
This is so great. I'll give it a look and see if I can clarify any items.

**Comment by kielejocain** [comment]
Thanks, @markawhitaker! I compiled a list of questions I know I had in #44, but if you have the time to give it a once over that would be great, too.

**Comment by kielejocain** [comment]
It's did.
