### ISSUE TITLE
fblocks.resp_zone not joining to incident.fireblock

### ISSUE THREAD

**Issue by rcallihan** [hackoregon/emergency-response#67]
The fireblock geometry table does not join to the to fireblock field in the incident table. There at least two (possibly more) reasons: 

- The `incident.fireblock` values have extra spaces padded on the right (at least two). 
- There are possibly some typos in the incident.fireblock values. (if you remove spaces, there are still ~138 more unique fireblocks in `incident.fireblock` than in `fblocks.resp_zone`.

We can either have logic to deal with this on the front-end or fix the values in the db. First, work we will need to figure out the source of the non-joins.

**Comment by rcallihan** [comment]
There's a related issue here of many fields in the incident table having trailing spaces. Possibly warrants a separate issue @sky-t @russellgould ?

**Comment by futurechris** [comment]
Also just in general, a question here which we should maybe open as a separate ticket: should we be cleaning all this stuff in our database, or should we be helping Mark do so and then we all benefit from the cleaned data?

@matthino has been finding some strange data re:FMA entries (instead of integers with values ~0 through ~30, getting 'GRESHAM' or '210' or something). Do we clean it? Just drop the bad data? etc.

**Comment by sky-t** [comment]
@russellgould cleaned the incident table (extra spaces from the varchar fields) so hopefully the join is working now. Has anyone else observed any other fields in any tables with extra spaces?

**Comment by russellgould** [comment]
I did! And actually @rcallihan said the join worked afterwards so I'll close this issue since it's resolved. If there are any other problems that pop up involving extraneous spaces feel free to open a separate issue and assign me and I'll get on it!
