### ISSUE TITLE
Create tables for domain stat rollups

### ISSUE THREAD

**Issue by hannahkane** [hackoregon/emergency-response#77]
We're looking for:
 - average response times per FMA 
 - average # of incidents per week per FMA

**Comment by futurechris** [comment]
In general, we want to compute response times ( #26 ) and then dump them into a table with FMA ID as primary key.

This will be the same table where we store the FMA-specific demographic stats for #75.

Mostly, this is straightforward, but there are two important questions to be answered:
1. Do we want to compute just the per-incident values (total time on scene counting all responders), or do we want to include per-responder values where it makes sense?
2. Do we want to compute this for just 2016, should it be for the entire dataset (2010-2016), or should we compute it per-year?
a. If per-year, where do we store that?

These are open for discussion.

Suggested initial answers to these questions, from discussion during tonight's meeting (3/22):
1. Compute per-incident, because it's simpler for now.
2. Compute over entire dataset, since data doesn't change that much over time.
a. This becomes N/A, given the above answer.

Any thoughts?

**Comment by matthino** [comment]
@futurechris The suggested initial answers sounds good to me. 

As far as "average" goes, are we still going to use the median?

**Comment by futurechris** [comment]
Yeah, I think median is probably more appropriate - we were just using 'Average' conversationally, hard habit to break.

In support of median: NFPA standards say "<6 minutes for 90% of calls", so 'median-style' metrics are already appropriate for the domain.

For that matter, we could actually mention the NFPA standard somewhere in the UX, might be interesting to users. I think PF&D handily beats the NFPA standard, though I haven't calculated that to be certain.

**Comment by sky-t** [comment]
I added median_response_time by FMA to the `fma_api_rollup`. Next onto average # of incidents per week per FMA.

**Comment by sky-t** [comment]
Updated `fma_api_rollup` to include average number of incidents per week by FMA. Going to close this ticket now unless you guys want to add anything else.
